apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apilambda-template
  title: Apilambda-Template Repository
  type: service
  description: |
    Repositorio principal de templates de Backstage para AWS Lambda y DynamoDB.

    Este repositorio contiene una colección completa de templates para generar servicios
    serverless con arquitecturas canónicas, incluyendo:

    - Templates de Backstage parametrizables
    - Funciones Lambda con operaciones CRUD
    - Configuración DynamoDB optimizada
    - Herramientas de testing integradas
    - Documentación automática con TechDocs
    - Políticas IAM con permisos mínimos

    Ideal para equipos que buscan acelerar el desarrollo de APIs serverless robustas.
  annotations:
    github.com/project-slug: Miguna/Apilambda-Template
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/Miguna/Apilambda-Template/tree/main/
  tags:
    - platform-engineering
    - backstage
    - templates
    - aws
    - lambda
    - dynamodb
    - serverless
    - crud
    - nodejs
    - infrastructure
    - devops
    - scaffolding
  links:
    - url: https://github.com/Miguna/Apilambda-Template
      title: GitHub Repository
      icon: github
    - url: https://github.com/Miguna/Apilambda-Template/blob/main/backstage-templates/lambda-dynamodb-crud/template.yaml
      title: Main Template
      icon: code
    - url: https://github.com/Miguna/Apilambda-Template/issues
      title: Issues & Support
      icon: help
    - url: https://docs.aws.amazon.com/lambda/
      title: AWS Lambda Documentation
      icon: cloud
    - url: https://backstage.io/docs/features/software-templates/
      title: Backstage Templates Documentation
      icon: docs
spec:
  type: library
  owner: development
  lifecycle: production
  providesApis:
    - apilambda-template-api
