site_name: Apilambda-Template
site_description: Repositorio de Templates de Backstage para AWS Lambda y DynamoDB
site_url: https://miguna.github.io/Apilambda-Template/
repo_url: https://github.com/Miguna/Apilambda-Template
repo_name: Miguna/Apilambda-Template

nav:
  - Inicio: index.md
  - Guía de Inicio Rápido: getting-started.md
  - Templates:
    - Overview: templates/index.md
    - Lambda DynamoDB CRUD: templates/lambda-dynamodb-crud.md
  - Desarrollo:
    - Arquitectura: development/architecture.md
    - Crear Nuevos Templates: development/creating-templates.md
    - Testing: development/testing.md
  - Deployment:
    - Configuración Backstage: deployment/backstage-setup.md
    - AWS Setup: deployment/aws-setup.md
  - Referencia:
    - API Reference: reference/api.md
    - Variables de Template: reference/template-variables.md
    - Troubleshooting: reference/troubleshooting.md
  - Contribuir: contributing.md

plugins:
  - techdocs-core
  - search
  - git-revision-date-localized:
      type: date

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Miguna/Apilambda-Template
  version:
    provider: mike
    default: latest

extra_css:
  - stylesheets/extra.css