site_name: Apilambda-Template
site_description: Repositorio de Templates de Backstage para AWS Lambda y DynamoDB

nav:
  - Inicio: index.md
  - Guía de Inicio: getting-started.md
  - Templates: templates/index.md

plugins:
  - techdocs-core

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc
