export const baseEvent = {
  version: '2.0',
  routeKey: '',
  rawPath: '',
  rawQueryString: '',
  headers: {},
  queryStringParameters: null,
  requestContext: {
    accountId: 'local-development',
    apiId: '${{ values.projectName }}-local',
    authorizer: {
      userId: 'local-user-id',
      accountId: 'local-account-id',
      email: 'developer@${{ values.destination.owner }}.com',
      role: 'developer',
    },
    domainName: 'localhost',
    domainPrefix: 'localhost',
    http: {
      method: '',
      path: '',
      protocol: 'HTTP/1.1',
      sourceIp: '127.0.0.1',
      userAgent: '${{ values.projectName }}-local-simulator',
    },
    requestId: 'local-request-id',
    routeKey: '',
    stage: 'local',
    time: '',
    timeEpoch: 0,
  },
  body: '',
  isBase64Encoded: false,
};